
/process/verbose 1
/process/em/verbose 1
/process/eLoss/verbose 1

##/particle/verbose 1
/run/verbose 1
##/event/verbose 1
/cuts/verbose 1


#/Sim/stepping/printProcess true
#/Sim/stepping/printProcessPerParticle true
#/Sim/stepping/printEnergy true
#/Sim/hits/printParticleEnergy proton
#/Sim/hits/printParticleEnergy all
#/Sim/det/detector  SNSDet #SNSTargetDetector #
#/run/reinitializeGeometry
#/process/eLoss/StepFunction 0.2 1 um
#/Sim/particle/DistrBoxSize 1 1 1 m


#/process/em/setSecBiasing eIoni World 0.3 2 MeV
#/run/setCutForAGivenParticle proton 1. mm # e- e+ gamma proton CAUTION
#/random/setSeeds x y


/process/eLoss/fluct false
/run/particle/applyCuts all  # gamma,e-,e+
/process/em/applyCuts  true
/run/getCutForAGivenParticle  proton #gamma,e-,e+
/run/getCutForAGivenParticle  gamma
/run/getCutForAGivenParticle  e-
/run/getCutForAGivenParticle  e+

#/Sim/parallel/parallelNum 25


##/tracking/verbose 1
/run/printProgress 1000

/run/setCut 1. mm  
/run/setCutForRegion BasementIn 10. mm #bulk shield too
/run/setCutForRegion BasementLayer 1. mm #bulk shield too
#/run/setCutForRegion Det_CsI 1. um #low cut

#/physics_engine/neutron/energyLimit 5. MeV
#/Sim/Kill/SetGammaThreshold 5. MeV

#/Sim/Kill/SetNeutronThreshold 1. MeV
/Sim/particle/name proton 
/Sim/particle/energy 940 MeV
#/Sim/particle/DistrSphereRadius 15 cm
#/Sim/particle/SetRandomBeamDir
/Sim/particle/position 0. -0.5 0. m
/Sim/particle/DistrBoxSize 0 0 0 cm
/Sim/particle/direction 0. 1. 0.
/physics_engine/neutron/timeLimit 1.0 s

# /gps/ang/type beam2d #Plane
# /gps/pos/shape Ellipsoid # Annulus, Circle, Square or Rectangle
# /gps/pos/centre 0. -0.5 0. m
# /gps/direction 0. 1. 0.
# /gps/pos/halfx 3.5 cm
# /gps/pos/halfy 10.0 cm
# /gps/pos/sigmax 2.
# /gps/pos/sigmay 2.

/Sim/FileNamePattern par1

/run/beamOn 10000
