/vis/open OGLSXm  #600x600-0+0 #laptop
#/vis/open OGLIXm  #office
#/vis/open OGLIX

/vis/ogl/set/displayListLimit 5000000

#/vis/ogl/set/eventsDrawInterval [interval]
#/vis/ogl/set/endTime [end-time] [end-time-unit] [time-range] [time-range-unit]
#/vis/ogl/set/printMode pixmap
#/vis/ogl/set/printSize 1000 1000
#/vis/ogl/printEPS

#/vis/open HepRepXML #use for jas
#/vis/open DAWNFILE
#/vis/open RayTracerX
#/vis/open HepRepFile

/vis/viewer/zoom 1
#/vis/sceneHandler/attach
/vis/drawVolume

# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh true #false
/vis/verbose errors

/vis/scene/add/hits
/vis/scene/add/trajectories
#/vis/scene/endOfEventAction accumulate #refresh
#/vis/scene/endOfRunAction accumulate #refresh
#/vis/scene/add/userAction
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/scale 10 m
#To start a new picture, you must explicitly issue /vis/viewer/refresh, /vis/viewer/update or /vis/viewer/flush

#/vis/viewer/set/viewpointVector 0.5 0.5 0
#/vis/viewer/set/background white
#/vis/viewer/set/projection perspective 10 deg

#To add attributes to each point on a trajectory, use:
#/vis/heprep/addPointAttributes 1
#/vis/viewer/set/hiddenMarker true
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 70 0 # 70 -45 #70 -10 
#/vis/viewer/set/upThetaPhi 
#/vis/viewer/set/auxiliaryEdge    #view sphere
#/vis/geometry/set/forceSolid
/vis/viewer/set/style wireframe
#/vis/viewer/set/style surface
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/visibility SNSTargetLogical 0 false
#/vis/touchable/set/daughtersInvisible true
#/vis/geometry/set/visibility HgSteelBoxLog 0 false
#/vis/geometry/set/visibility UpperBePlugLog 0 false
#/vis/geometry/set/visibility LowerBePlugLog 0 false
#/vis/geometry/set/visibility InnerSteelD2O_1Log 0 false
#/vis/geometry/set/visibility InnerSteelD2O_2Log 0 false
#/vis/geometry/set/visibility OuterSteelLog 0 false
#/vis/geometry/set/visibility MonoSteelLog 0 false
#/vis/geometry/set/visibility OuterProtonBoxConcreteLog 0 false
#/vis/geometry/set/visibility OuterProtonBoxSteelBoxLog 0 false
#/vis/geometry/set/visibility OuterProtonBoxHDBoxLog 0 false
#/vis/geometry/set/visibility OuterProtonBoxSteelInOuterLog 0 false
#/vis/geometry/set/visibility BulkNBeamConcShieldLog 0 false
#/vis/geometry/set/visibility BasementLog 0 false
#/vis/geometry/set/visibility TunnelWallLog 0 false
#/vis/geometry/set/visibility basementRoofTopLog 0 false
#/vis/geometry/set/visibility basementRoofStoneLog 0 false
#/vis/geometry/set/visibility basementRoofInLog 0 false
#/vis/geometry/set/visibility DetPbLog  0 false
#/vis/geometry/set/visibility DetPolyLog  0 false
#/vis/geometry/set/visibility DetCsILog  0 false
#/vis/geometry/set/visibility AirVolumeLog 0 false


#/vis/viewer/addCutawayPlane 0 0 0 m -1 0 0 
#/vis/viewer/set/sectionPlane  on  50.0  0.0  0.0  cm  10.0  0.0  0.0

  #/vis/scene/create
  #/vis/scene/add/logicalVolume SNSParallelWorld
  #/vis/sceneHandler/attach
#/vis/drawVolume SNSParallelWorld
#/vis/specify SNSParallelWorld

/vis/scene/add/logicalVolume SNSParallelWorld
/vis/drawVolume SNSParallelWorld
/vis/geometry/set/visibility SNSParallelWorld 0 false
/vis/viewer/flush

#/vis/scene/add/eventID 
#/vis/viewer/clear
#/vis/viewer/zoom 2

/physics_engine/neutron/timeLimit 1.0 s
/Sim/particle/name proton 
/Sim/particle/energy 1000 MeV
#/Sim/particle/DistrSphereRadius 15 cm
/Sim/particle/position 0. -0.5 0. m
/Sim/particle/DistrBoxSize 0 0 0 cm
/Sim/particle/direction 0. 1. 0.

/run/beamOn 1
